# This is a basic workflow to help you get started with Actions

name: Validate Riscatto Punti Canale Gravier

# Controls when the action will run. 
on:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate-riscatto-punti-canale-gravier:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13 #install the python needed

      - name: install required packages
        run: |
          pip install gspread oauth2client
          pip install --upgrade google-api-python-client
      - name: set-environment-vars
        uses: microsoft/variable-substitution@v1 
        id: create-env
        with:
          files: './data/riscattoPuntiCanale.json'
        env:
          private_key_id: ${{ secrets.PRIVATE_KEY_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_email: ${{ secrets.CLIENT_EMAIL }}
          client_x509_cert_url: ${{ secrets.CLIENT_CERT_URI }}
          
      - name: execute py script
        run: |
            python3 RiscattoPuntiCanaleGravier.py --json ./data/riscattoPuntiCanale.json
        
